/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Carlos
 */
public class VtnAgrega_oModificaEventoSocial extends javax.swing.JFrame {

    private static VtnAgrega_oModificaEventoSocial 
            instanciaVtnAgregaoModificaEventoSocial = new VtnAgrega_oModificaEventoSocial();

    private boolean seModificaraEventoSocial;
    /**
     * Creates new form VtnAgrega_oModificaEventoSocial
     */
    public VtnAgrega_oModificaEventoSocial() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
        public static VtnAgrega_oModificaEventoSocial getInstanciaDeVtnAgrega_oModificaEventoSocial() {
        return instanciaVtnAgregaoModificaEventoSocial;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardarEvento = new javax.swing.JButton();
        cbBanqueteraEvento = new javax.swing.JCheckBox();
        cbCarpaEvento = new javax.swing.JCheckBox();
        cbLucesEvento = new javax.swing.JCheckBox();
        cbLugarEvento = new javax.swing.JCheckBox();
        cbMesaDulcesEvento = new javax.swing.JCheckBox();
        cbMusicaEvento = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btnRegresarVtnEventosSociales = new javax.swing.JButton();
        txtNombreCliente = new javax.swing.JTextField();
        txtFechaEvento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Evento");

        btnGuardarEvento.setText("Guardar");

        cbBanqueteraEvento.setText("Banquetera");

        cbCarpaEvento.setText("Carpa");
        cbCarpaEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCarpaEventoActionPerformed(evt);
            }
        });

        cbLucesEvento.setText("Luces");

        cbLugarEvento.setText("Lugar");

        cbMesaDulcesEvento.setText("Mesa de Dulces");

        cbMusicaEvento.setText("Música");
        cbMusicaEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMusicaEventoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Evento");

        btnRegresarVtnEventosSociales.setText("Regresar");
        btnRegresarVtnEventosSociales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarVtnEventosSocialesActionPerformed(evt);
            }
        });

        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });

        txtFechaEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaEventoActionPerformed(evt);
            }
        });

        jLabel2.setText("Cliente:");

        jLabel3.setText("Fecha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuardarEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresarVtnEventosSociales))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNombreCliente)
                                            .addComponent(txtFechaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(cbLucesEvento)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(cbMusicaEvento))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(cbBanqueteraEvento)
                                                    .addGap(58, 58, 58)
                                                    .addComponent(cbLugarEvento)
                                                    .addGap(4, 4, 4)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbCarpaEvento)
                                                .addGap(84, 84, 84)
                                                .addComponent(cbMesaDulcesEvento)))))))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBanqueteraEvento)
                    .addComponent(cbLugarEvento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCarpaEvento)
                    .addComponent(cbMesaDulcesEvento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLucesEvento)
                    .addComponent(cbMusicaEvento))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarEvento)
                    .addComponent(btnRegresarVtnEventosSociales))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCarpaEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCarpaEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCarpaEventoActionPerformed

    private void cbMusicaEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMusicaEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMusicaEventoActionPerformed

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void txtFechaEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaEventoActionPerformed

    private void btnRegresarVtnEventosSocialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarVtnEventosSocialesActionPerformed
        // TODO add your handling code here:
        VtnEventosSociales vtnRegreso = VtnEventosSociales.getInstanciaDeVtnEventosSociales();
        vtnRegreso.setVisible(true);
        cerrarEstaVentana();
        
        
    }//GEN-LAST:event_btnRegresarVtnEventosSocialesActionPerformed

        private void cerrarEstaVentana() {
        //borraDatosDeCampos();
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaEventoSocial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaEventoSocial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaEventoSocial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaEventoSocial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnAgrega_oModificaEventoSocial().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarEvento;
    private javax.swing.JButton btnRegresarVtnEventosSociales;
    private javax.swing.JCheckBox cbBanqueteraEvento;
    private javax.swing.JCheckBox cbCarpaEvento;
    private javax.swing.JCheckBox cbLucesEvento;
    private javax.swing.JCheckBox cbLugarEvento;
    private javax.swing.JCheckBox cbMesaDulcesEvento;
    private javax.swing.JCheckBox cbMusicaEvento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtFechaEvento;
    private javax.swing.JTextField txtNombreCliente;
    // End of variables declaration//GEN-END:variables
}
