/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorClientes;
import Controlador.ControladorMesaDeDulces;
import Modelo.Cliente;
import Modelo.Mesa_de_dulces;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro
 */
public class VtnAgrega_oModificaMesaDeDulces extends javax.swing.JFrame {

    private static VtnAgrega_oModificaMesaDeDulces instanciaVtnAgregaoModificaMesaDeDulces = new VtnAgrega_oModificaMesaDeDulces();
    private boolean seModificaraMesaDeDulces;

    /**
     * Creates new form VtnAgrega_oModificaMesaDeDulces
     */
    public VtnAgrega_oModificaMesaDeDulces() {
        initComponents();
        setLocationRelativeTo(null);
        seModificaraMesaDeDulces = false;
    }

    public static VtnAgrega_oModificaMesaDeDulces getInstanciaVtnAgrega_oModificaMesaDeDulces() {
        return instanciaVtnAgregaoModificaMesaDeDulces;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombreMesaDulces = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPrecioMesaDulces = new javax.swing.JTextField();
        btnGuardarMesaDulces = new javax.swing.JButton();
        btnRegresarVtnMesaDeDulces = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Mesa de Dulces");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mesa de Dulces");

        txtNombreMesaDulces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreMesaDulcesActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Precio:");

        btnGuardarMesaDulces.setText("Guardar");
        btnGuardarMesaDulces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMesaDulcesActionPerformed(evt);
            }
        });

        btnRegresarVtnMesaDeDulces.setText("Regresar");
        btnRegresarVtnMesaDeDulces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarVtnMesaDeDulcesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuardarMesaDulces)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresarVtnMesaDeDulces))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreMesaDulces)
                            .addComponent(txtPrecioMesaDulces, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreMesaDulces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrecioMesaDulces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarMesaDulces)
                    .addComponent(btnRegresarVtnMesaDeDulces))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarVtnMesaDeDulcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarVtnMesaDeDulcesActionPerformed
        // TODO add your handling code here:
        VtnMesaDeDulces vtnRegreso = VtnMesaDeDulces.getInstanciaDeVtnMesaDeDulces();
        vtnRegreso.setVisible(true);
        cerrarEstaVentana();
    }//GEN-LAST:event_btnRegresarVtnMesaDeDulcesActionPerformed

    private void mensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje, "Cuidado", 0);
    }
    private void btnGuardarMesaDulcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMesaDulcesActionPerformed
        // TODO add your handling code here:
        //Primero obtenemos los datos del cliente
        //y las guardamos en las siguientes variables:
        String nombre = this.txtNombreMesaDulces.getText();
        String precio = this.txtPrecioMesaDulces.getText();
        
                
        //Creamos la variable temporal de cliente.
        Mesa_de_dulces tempMesaDeDulces = new Mesa_de_dulces(nombre,Float.valueOf(precio));
        ControladorMesaDeDulces ctrlMesaDeDulces = new ControladorMesaDeDulces();
        
        
        try {
            if (!seModificaraMesaDeDulces) {
                boolean seAgregoMesaDeDulces = ctrlMesaDeDulces.agregarMD(tempMesaDeDulces);
                 if (seAgregoMesaDeDulces) mensaje("Cliente Agregado");
                 else mensaje("Mesa de Dulces No Agregada");
                
            }else{
                //Hace Falta pulir modificarMD en el controlador de mesa de Dulces
                boolean seModificoMesaDeDulces = ctrlMesaDeDulces.modificarMD(tempMesaDeDulces);
                 if (seModificoMesaDeDulces) mensaje("Cliente Modificado");
                 else  mensaje("Cliente No Modificado");
                 //lo devolvemos a su estado de inicio.
                seModificaraMesaDeDulces = false;
            }
        } catch (SQLException ex) {
            mensaje("Hubo un error con la "
                    + "base de datos. " + ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnGuardarMesaDulcesActionPerformed

    private void txtNombreMesaDulcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreMesaDulcesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMesaDulcesActionPerformed

    private void borraDatosDeCampos() {
        this.txtNombreMesaDulces.setText("");
        this.txtPrecioMesaDulces.setText("");
        
    }

    private void cerrarEstaVentana() {
        borraDatosDeCampos();
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaMesaDeDulces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaMesaDeDulces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaMesaDeDulces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaMesaDeDulces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnAgrega_oModificaMesaDeDulces().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarMesaDulces;
    private javax.swing.JButton btnRegresarVtnMesaDeDulces;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNombreMesaDulces;
    private javax.swing.JTextField txtPrecioMesaDulces;
    // End of variables declaration//GEN-END:variables
}
